<?php
/**
 * Manages robots.txt crawler rules
 *
 * @link       https://techbysh.com
 * @since      1.0.0
 *
 * @package    Tavc
 * @subpackage Tavc/includes
 */

// If this file is called directly, abort.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Manages robots.txt crawler rules.
 *
 * Filters the robots.txt output to append blocks for selected AI crawlers
 * while preserving existing rules generated by other plugins or settings.
 *
 * @since      1.0.0
 * @package    Tavc
 * @subpackage Tavc/includes
 * @author     Techbysh
 */
class TAVC_Bot_Manager {

	/**
	 * Append disallow rules for selected AI bots to robots.txt output.
	 *
	 * @since    1.0.0
	 * @param    string    $output    The robots.txt content.
	 * @param    bool      $public    Whether the site is public.
	 * @return   string               The modified robots.txt content.
	 */
	public function add_robots_txt_rules( $output, $public ) {
		// If the site is not public, WordPress blocks all bots by default.
		// However, we still append selected blocks for completeness.
		
		$blocked_bots = get_option( 'tavc_blocked_bots', array() );
		if ( empty( $blocked_bots ) || ! is_array( $blocked_bots ) ) {
			return $output;
		}

		// Map stored slugs to official User-Agent names
		$bot_mapping = array(
			'gptbot'            => 'GPTBot',
			'claudebot'         => 'ClaudeBot',
			'perplexitybot'     => 'PerplexityBot',
			'google-extended'   => 'Google-Extended',
			'ccbot'             => 'CCBot',
			'amazonbot'         => 'Amazonbot',
			'applebot-extended' => 'Applebot-Extended',
		);

		$rules = '';

		foreach ( $bot_mapping as $slug => $user_agent ) {
			if ( ! empty( $blocked_bots[ $slug ] ) ) {
				$rules .= "\n";
				$rules .= "User-agent: " . $user_agent . "\n";
				$rules .= "Disallow: /\n";
			}
		}

		if ( ! empty( $rules ) ) {
			$output .= "\n# " . __( 'AI Visibility Control Rules', 'tbsh-ai-visibility-control' ) . "\n" . $rules;
		}

		return $output;
	}
}
